import Card from "../../ui/Card";

const Capabilities = () => {
  const sections = [
    {
      id: "I",
      title: "ABOUT",
      subtitle: "INFORMATION",
      content: `TITO ZAKI SAPUTRO IS A DYNAMIC FULL-STACK DEVELOPER AND COMPUTER SCIENCE STUDENT AT UNIVERSITAS TEKNOLOGI YOGYAKARTA (UTY) WITH A PROVEN TRACK RECORD IN BUILDING SCALABLE WEB AND MOBILE APPLICATIONS. PROFICIENT IN MODERN TECHNOLOGIES INCLUDING REACT, TYPESCRIPT, NODE.JS, AND FLUTTER, HE HAS SUCCESSFULLY DELIVERED MULTIPLE CLIENT PROJECTS WHILE MAINTAINING ACADEMIC EXCELLENCE. TITO'S DEVELOPMENT APPROACH COMBINES CLEAN CODE PRINCIPLES WITH USER-CENTRIC DESIGN, RESULTING IN PERFORMANT AND INTUITIVE APPLICATIONS. HIS RECENT PROJECTS INCLUDE AN E-COMMERCE PLATFORM WITH 10K+ MONTHLY USERS AND A CROSS-PLATFORM MOBILE APP FOR LOCAL BUSINESSES. CURRENTLY SEEKING OPPORTUNITIES TO LEVERAGE HIS TECHNICAL EXPERTISE IN A CHALLENGING DEVELOPMENT ROLE.`,
    },
  ];
  return (
    <section>
      <div className="mx-auto w-full min-h-dvh">
        <div className="flex flex-col p-8 text-left">
          <div className="flex justify-start items-start">
            <Card sections={sections} />
          </div>
        </div>
      </div>
    </section>
  );
};

export default Capabilities;
